[main]
;---- ledgers items closingstock outstanding

iseducational=0

post journal=1
receipt voucher type=SZ_Receipt
journal voucher type name=SZ_Journal
stock journal voucher type=SZ_Stock Journal

------ Entry Time Auto Create
Item Auto Create=0
ledger Auto Create=0
costcentre auto create=0

defaultmainlocation=0

-- First Auto Create Then Post Primary sales
Post Item In Tally=1
Post ledger In Tally=1
stopmasterupdate=1
Post Party Ledger in tally=1
isprimarybatch=1
post dummy item=1

Created On Days=7
postitemnamewise=1


loggingenabled=1
logall=1
;pgdebugmodes=406

server=localhost:9000
statename=west bengal
Freight Ledger=Delivery Expenses


;----------------------(actualqty and billqty NOT show) if 1
NOT DIFFACTUALQTY=1

;----------------enable Payments (Coeptis)
isenablepayment=1
issinglevouchertype=1
Receipt voucher type Name= receipt
Purchase VoucherType= Purchase Bill GST
Purchase Ledger= Purchase A/C
postitemnamewise=0

;------------for Purchase  dynamic
isecomvouchertype=43



Sales Return Local Sales Ledger= Sales Local - GST
Sales Return Interstate Sales Ledger= Sales Interstate - GST

;------------------ Saleszing To Tally Post
sztotally=1

;---------------------for no branch code in ps json file
isbranchcodeos=0


VoucherType= SZ Sales Order
Primary Sales Voucher Type=SALES BILL GST


dbpath=D:\Posting Setup\DB\APISynchberger.ABS

Local Sales Ledger=Sales Local - GST
Interstate Sales Ledger=Sales Interstate - GST

;Godown Name=Finished Goods Godown (TRD)



Sales Return Godown Name=Rejection Material Return Godown

PDFFilepath=E:\works\CenturyLED\docs

CGST Ledger=Output CGST
SGST Ledger= Output SGST
IGST Ledger= Output IGST

;----------------------------Secondary Sales
SHour=08
Smin=57

deletebeforpost=1
hide tally error=1
Show tally Error=0
useclipboard=1
tallyupdate=1

isauto=1
isgstledger=1
enablereceipt=0
enablebranch=0
ItemImporttype=0
enable Item Wise Sales ledger=1
enable sample issue=1



autoled=0

;autopsales=0
autoexportpdf=0
;autopurchase=0


autopsales=1
autopurchase=1
autoreceipt=1
autopayment=1
autostocktransfer=1
autopurchasereturn=1
autosalesreturn=1




Scheme CreditNote Godown Name= main location

Default Leder Group Parent=Sundry Debtors


sample issue vouchertype id=159
sample issue subdoctype id=5
enable item wise=1

----
purchase Base doctype id=13
Enable Purchase Return=1

Purchase Return voucher type id=163
Purchase Return VoucherType= Purchase Return



multiuominitemmaster=0
check item exists in tally=1
check ledger exists in tally=1
check itemname wise=1